### ISSUE TITLE
Opcode Not Found Error While Running `evm-verifier` Test

### ISSUE THREAD

**Issue by shreyas-londhe** [axiom-crypto/snark-verifier#45]
HI, I'm trying to the run the test for `evm-verifier` and it is giving an error while deploying as Opcode not found. 

I ran it with the command `cargo run --example evm-verifier --release --features loader_evm`

Any help is much appreciated.

Thanks!

**Comment by jonathanpwang** [comment]
Try using `solc` version 0.8.19
